<?php

namespace Database\Seeders;

use App\Models\Feature;
use Illuminate\Database\Seeder;

class FeatureSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $features = [
            // ==================== SEGURIDAD, ACCESO & ROLES ====================
            [
                'category' => 'Seguridad & Acceso',
                'name' => 'Autenticación Avanzada Multi-Rol y 2FA',
                'slug' => 'auth-multi-role-2fa',
                'description' => 'Control de acceso granular por permisos (Spatie/Policies), autenticación en 2 pasos (OTP/Authenticator) y registro de sesiones activas.',
                'hours_dev' => 6.00,
                'hours_integration' => 6.00,
                'hours_testing_qa' => 8.00,
                'cost_setup_infra' => 0.00,
                'cost_monthly_infra' => 15.00,
                'is_preset_mining' => true,
                'is_preset_environment' => true,
                'is_preset_commerce' => true,
                'is_preset_industry' => true,
                'is_preset_services' => true,
                'is_recommended' => true,
            ],
            [
                'category' => 'Seguridad & Acceso',
                'name' => 'Auditoría de Acciones y Trazabilidad Forense',
                'slug' => 'audit-logs-compliance',
                'description' => 'Log inmutable de cambios (quién, qué, cuándo y desde qué IP) para cumplimiento de normas ISO 9001 / ISO 45001 / ISO 14001 y auditorías externas.',
                'hours_dev' => 5.00,
                'hours_integration' => 7.00,
                'hours_testing_qa' => 8.00,
                'cost_setup_infra' => 20.00,
                'cost_monthly_infra' => 25.00,
                'is_preset_mining' => true,
                'is_preset_environment' => true,
                'is_preset_commerce' => false,
                'is_preset_industry' => true,
                'is_preset_services' => true,
                'is_recommended' => true,
            ],

            // ==================== MINERÍA, HSE & OPERACIONES EN FAENA ====================
            [
                'category' => 'Minería & HSE',
                'name' => 'Telemetría y Monitoreo de Sensores en Tiempo Real',
                'slug' => 'iot-sensors-mining',
                'description' => 'Recepción y procesamiento de datos de telemetría de maquinaria y sensores de gases/vibración vía WebSockets / MQTT.',
                'hours_dev' => 10.00,
                'hours_integration' => 14.00,
                'hours_testing_qa' => 16.00,
                'cost_setup_infra' => 80.00,
                'cost_monthly_infra' => 60.00,
                'is_preset_mining' => false,
                'is_preset_environment' => false,
                'is_preset_commerce' => false,
                'is_preset_industry' => false,
                'is_preset_services' => false,
                'is_recommended' => false,
            ],
            [
                'category' => 'Minería & HSE',
                'name' => 'Mapeo GIS Satelital y Geofencing de Faena',
                'slug' => 'gis-geofencing-mining',
                'description' => 'Visualización de vehículos y cuadrillas en mapa interactivo con delimitación de zonas seguras y alertas de desvío.',
                'hours_dev' => 8.00,
                'hours_integration' => 12.00,
                'hours_testing_qa' => 12.00,
                'cost_setup_infra' => 50.00,
                'cost_monthly_infra' => 45.00,
                'is_preset_mining' => false,
                'is_preset_environment' => false,
                'is_preset_commerce' => false,
                'is_preset_industry' => false,
                'is_preset_services' => false,
                'is_recommended' => false,
            ],
            [
                'category' => 'Minería & HSE',
                'name' => 'Sincronización Offline-First para Terreno',
                'slug' => 'offline-sync-mobile',
                'description' => 'Almacenamiento local en dispositivo móvil (IndexedDB / SQLite local) con sincronización bidireccional automática al recuperar conectividad.',
                'hours_dev' => 12.00,
                'hours_integration' => 16.00,
                'hours_testing_qa' => 20.00,
                'cost_setup_infra' => 30.00,
                'cost_monthly_infra' => 20.00,
                'is_preset_mining' => false,
                'is_preset_environment' => false,
                'is_preset_commerce' => false,
                'is_preset_industry' => false,
                'is_preset_services' => false,
                'is_recommended' => false,
            ],
            [
                'category' => 'Minería & HSE',
                'name' => 'Gestión de Contratistas y Control de EPP',
                'slug' => 'contractors-epp-management',
                'description' => 'Validación de aptitud médica, ART, inducciones de seguridad y entrega de elementos de protección personal con firma digital.',
                'hours_dev' => 8.00,
                'hours_integration' => 8.00,
                'hours_testing_qa' => 10.00,
                'cost_setup_infra' => 0.00,
                'cost_monthly_infra' => 15.00,
                'is_preset_mining' => true,
                'is_preset_environment' => false,
                'is_preset_commerce' => false,
                'is_preset_industry' => true,
                'is_preset_services' => false,
                'is_recommended' => false,
            ],

            // ==================== MEDIO AMBIENTE & SUSTENTABILIDAD ====================
            [
                'category' => 'Medio Ambiente',
                'name' => 'Módulo de Mediciones Ambientales (Agua, Aire, Suelo)',
                'slug' => 'environmental-measurements',
                'description' => 'Carga y validación de ensayos de laboratorio, comparación automática contra límites legales y alertas tempranas de excedencia.',
                'hours_dev' => 8.00,
                'hours_integration' => 10.00,
                'hours_testing_qa' => 12.00,
                'cost_setup_infra' => 0.00,
                'cost_monthly_infra' => 20.00,
                'is_preset_mining' => false,
                'is_preset_environment' => true,
                'is_preset_commerce' => false,
                'is_preset_industry' => false,
                'is_preset_services' => false,
                'is_recommended' => true,
            ],
            [
                'category' => 'Medio Ambiente',
                'name' => 'Matriz de Cumplimiento Legal y Licencias Ambientales',
                'slug' => 'environmental-legal-matrix',
                'description' => 'Gestor de requisitos legales vigentes por provincia/nación, alertas de vencimiento de permisos y asignación de responsables.',
                'hours_dev' => 6.00,
                'hours_integration' => 8.00,
                'hours_testing_qa' => 10.00,
                'cost_setup_infra' => 0.00,
                'cost_monthly_infra' => 15.00,
                'is_preset_mining' => false,
                'is_preset_environment' => true,
                'is_preset_commerce' => false,
                'is_preset_industry' => true,
                'is_preset_services' => false,
                'is_recommended' => true,
            ],
            [
                'category' => 'Medio Ambiente',
                'name' => 'Generador de Informes Técnicos y Balances de Carbono',
                'slug' => 'environmental-reports-carbon',
                'description' => 'Cálculo de huella de carbono, generación de reportes en PDF formal listos para presentación ante entes reguladores y autoridades.',
                'hours_dev' => 7.00,
                'hours_integration' => 9.00,
                'hours_testing_qa' => 12.00,
                'cost_setup_infra' => 25.00,
                'cost_monthly_infra' => 20.00,
                'is_preset_mining' => true,
                'is_preset_environment' => true,
                'is_preset_commerce' => false,
                'is_preset_industry' => false,
                'is_preset_services' => false,
                'is_recommended' => false,
            ],

            // ==================== E-COMMERCE & COMERCIO ====================
            [
                'category' => 'Comercio & Pagos',
                'name' => 'Catálogo Inteligente, Filtros y Carrito de Compras',
                'slug' => 'catalog-cart-commerce',
                'description' => 'Gestión de productos con variantes (talle, color, especificaciones), buscador predictivo, listas de precios mayoristas y carrito persistente.',
                'hours_dev' => 8.00,
                'hours_integration' => 8.00,
                'hours_testing_qa' => 10.00,
                'cost_setup_infra' => 0.00,
                'cost_monthly_infra' => 15.00,
                'is_preset_mining' => false,
                'is_preset_environment' => false,
                'is_preset_commerce' => true,
                'is_preset_industry' => false,
                'is_preset_services' => false,
                'is_recommended' => true,
            ],
            [
                'category' => 'Comercio & Pagos',
                'name' => 'Pasarela de Pagos (Mercado Pago / Stripe / Transferencia)',
                'slug' => 'payment-gateway-integration',
                'description' => 'Checkout transparente, webhooks de confirmación automática de pagos, suscripciones recurrentes y soporte multi-moneda.',
                'hours_dev' => 6.00,
                'hours_integration' => 10.00,
                'hours_testing_qa' => 14.00,
                'cost_setup_infra' => 40.00,
                'cost_monthly_infra' => 20.00,
                'is_preset_mining' => false,
                'is_preset_environment' => false,
                'is_preset_commerce' => true,
                'is_preset_industry' => false,
                'is_preset_services' => true,
                'is_recommended' => false,
            ],
            [
                'category' => 'Comercio & Pagos',
                'name' => 'Facturación Electrónica AFIP / Facturación Automática',
                'slug' => 'afip-invoicing-integration',
                'description' => 'Integración directa con Web Services de AFIP (WSFE) para emisión instantánea de Facturas A, B, C y Notas de Crédito con CAE.',
                'hours_dev' => 6.00,
                'hours_integration' => 12.00,
                'hours_testing_qa' => 16.00,
                'cost_setup_infra' => 50.00,
                'cost_monthly_infra' => 30.00,
                'is_preset_mining' => false,
                'is_preset_environment' => false,
                'is_preset_commerce' => true,
                'is_preset_industry' => true,
                'is_preset_services' => true,
                'is_recommended' => false,
            ],
            [
                'category' => 'Comercio & Pagos',
                'name' => 'Integración Logística y Envíos (Andreani, Correo, OCA)',
                'slug' => 'logistics-shipping-api',
                'description' => 'Cotizador de envíos en tiempo real en checkout, generación de etiquetas de despacho con código de barras y tracking para el comprador.',
                'hours_dev' => 5.00,
                'hours_integration' => 9.00,
                'hours_testing_qa' => 12.00,
                'cost_setup_infra' => 30.00,
                'cost_monthly_infra' => 20.00,
                'is_preset_mining' => false,
                'is_preset_environment' => false,
                'is_preset_commerce' => false,
                'is_preset_industry' => false,
                'is_preset_services' => false,
                'is_recommended' => false,
            ],

            // ==================== INDUSTRIA & MANUFACTURA (NUEVO PRESET) ====================
            [
                'category' => 'Industria & Manufactura',
                'name' => 'Control de Órdenes de Producción y Trazabilidad de Lotes',
                'slug' => 'production-orders-traceability',
                'description' => 'Seguimiento de etapas de fabricación, asignación de operarios, control de mermas y trazabilidad completa de lotes con código QR.',
                'hours_dev' => 10.00,
                'hours_integration' => 12.00,
                'hours_testing_qa' => 14.00,
                'cost_setup_infra' => 30.00,
                'cost_monthly_infra' => 25.00,
                'is_preset_mining' => false,
                'is_preset_environment' => false,
                'is_preset_commerce' => false,
                'is_preset_industry' => true,
                'is_preset_services' => false,
                'is_recommended' => false,
            ],
            [
                'category' => 'Industria & Manufactura',
                'name' => 'Mantenimiento Preventivo & Correctivo de Maquinaria (CMMS)',
                'slug' => 'cmms-machine-maintenance',
                'description' => 'Planes de lubricación y calibración por horas de uso/kilometraje, órdenes de trabajo de taller mecánico y stock de repuestos críticos.',
                'hours_dev' => 8.00,
                'hours_integration' => 10.00,
                'hours_testing_qa' => 12.00,
                'cost_setup_infra' => 0.00,
                'cost_monthly_infra' => 20.00,
                'is_preset_mining' => true,
                'is_preset_environment' => false,
                'is_preset_commerce' => false,
                'is_preset_industry' => true,
                'is_preset_services' => false,
                'is_recommended' => true,
            ],
            [
                'category' => 'Industria & Manufactura',
                'name' => 'Control de Calidad en Línea y Ensayos de Planta',
                'slug' => 'plant-quality-control',
                'description' => 'Planillas de verificación de tolerancias, registro fotográfico de no conformidades y aprobación digital de lotes terminados.',
                'hours_dev' => 6.00,
                'hours_integration' => 8.00,
                'hours_testing_qa' => 10.00,
                'cost_setup_infra' => 0.00,
                'cost_monthly_infra' => 15.00,
                'is_preset_mining' => false,
                'is_preset_environment' => false,
                'is_preset_commerce' => false,
                'is_preset_industry' => true,
                'is_preset_services' => false,
                'is_recommended' => true,
            ],
            [
                'category' => 'Industria & Manufactura',
                'name' => 'Gestión de Stock de Materia Prima y Depósitos Múltiples',
                'slug' => 'raw-materials-multi-warehouse',
                'description' => 'Control de stock mínimo, punto de reorden, transferencias entre depósitos de planta y alertas de desabastecimiento.',
                'hours_dev' => 7.00,
                'hours_integration' => 9.00,
                'hours_testing_qa' => 12.00,
                'cost_setup_infra' => 0.00,
                'cost_monthly_infra' => 15.00,
                'is_preset_mining' => false,
                'is_preset_environment' => false,
                'is_preset_commerce' => true,
                'is_preset_industry' => true,
                'is_preset_services' => false,
                'is_recommended' => true,
            ],
            [
                'category' => 'Industria & Manufactura',
                'name' => 'Sensores IoT de Eficiencia OEE y Paradas de Línea',
                'slug' => 'iot-oee-factory-sensors',
                'description' => 'Monitoreo en tiempo real de disponibilidad, rendimiento y calidad de máquinas industriales con cálculo automático de OEE.',
                'hours_dev' => 12.00,
                'hours_integration' => 16.00,
                'hours_testing_qa' => 18.00,
                'cost_setup_infra' => 85.00,
                'cost_monthly_infra' => 65.00,
                'is_preset_mining' => false,
                'is_preset_environment' => false,
                'is_preset_commerce' => false,
                'is_preset_industry' => false,
                'is_preset_services' => false,
                'is_recommended' => false,
            ],

            // ==================== SERVICIOS & CONSULTORÍA (NUEVO PRESET) ====================
            [
                'category' => 'Servicios & Consultoría',
                'name' => 'Portal de Clientes y Mesa de Ayuda con Tickets SLA',
                'slug' => 'client-portal-helpdesk-sla',
                'description' => 'Canal de atención al cliente para apertura de solicitudes, seguimiento de estado, tiempos de respuesta SLA y satisfacción CSAT.',
                'hours_dev' => 8.00,
                'hours_integration' => 10.00,
                'hours_testing_qa' => 12.00,
                'cost_setup_infra' => 20.00,
                'cost_monthly_infra' => 20.00,
                'is_preset_mining' => false,
                'is_preset_environment' => false,
                'is_preset_commerce' => false,
                'is_preset_industry' => false,
                'is_preset_services' => true,
                'is_recommended' => true,
            ],
            [
                'category' => 'Servicios & Consultoría',
                'name' => 'Time Tracking y Registro de Horas Facturables por Proyecto',
                'slug' => 'time-tracking-billable-hours',
                'description' => 'Temporizador integrado por tarea, carga de horas por colaborador, cálculo de rentabilidad de proyectos y liquidación de honorarios.',
                'hours_dev' => 6.00,
                'hours_integration' => 8.00,
                'hours_testing_qa' => 10.00,
                'cost_setup_infra' => 0.00,
                'cost_monthly_infra' => 15.00,
                'is_preset_mining' => false,
                'is_preset_environment' => false,
                'is_preset_commerce' => false,
                'is_preset_industry' => false,
                'is_preset_services' => true,
                'is_recommended' => true,
            ],
            [
                'category' => 'Servicios & Consultoría',
                'name' => 'Gestión de Contratos de Servicio y Abonos Recurrentes',
                'slug' => 'service-contracts-recurring-billing',
                'description' => 'Administración de contratos de mantenimiento, emisión automática mensual de facturas recurrentes y control de límites de consumo.',
                'hours_dev' => 7.00,
                'hours_integration' => 11.00,
                'hours_testing_qa' => 14.00,
                'cost_setup_infra' => 25.00,
                'cost_monthly_infra' => 20.00,
                'is_preset_mining' => false,
                'is_preset_environment' => false,
                'is_preset_commerce' => false,
                'is_preset_industry' => false,
                'is_preset_services' => true,
                'is_recommended' => false,
            ],
            [
                'category' => 'Servicios & Consultoría',
                'name' => 'Agenda Inteligente y Gestión de Turnos / Citas Online',
                'slug' => 'appointment-booking-calendar',
                'description' => 'Reserva de turnos online para clientes, sincronización con Google Calendar / Outlook y recordatorios automáticos por WhatsApp.',
                'hours_dev' => 6.00,
                'hours_integration' => 10.00,
                'hours_testing_qa' => 12.00,
                'cost_setup_infra' => 20.00,
                'cost_monthly_infra' => 20.00,
                'is_preset_mining' => false,
                'is_preset_environment' => false,
                'is_preset_commerce' => false,
                'is_preset_industry' => false,
                'is_preset_services' => true,
                'is_recommended' => false,
            ],
            [
                'category' => 'Servicios & Consultoría',
                'name' => 'Firma Digital de Actas de Servicio y Conformidad',
                'slug' => 'digital-signature-service-orders',
                'description' => 'Captura de firma manuscrita digital en tablet/móvil al finalizar visitas técnicas o consultorías con envío automático de copia PDF.',
                'hours_dev' => 5.00,
                'hours_integration' => 7.00,
                'hours_testing_qa' => 8.00,
                'cost_setup_infra' => 0.00,
                'cost_monthly_infra' => 10.00,
                'is_preset_mining' => true,
                'is_preset_environment' => false,
                'is_preset_commerce' => false,
                'is_preset_industry' => true,
                'is_preset_services' => true,
                'is_recommended' => true,
            ],

            // ==================== AUTOMATIZACIÓN, IA & CHATBOTS ====================
            [
                'category' => 'IA & Automatizaciones',
                'name' => 'Chatbot Inteligente con WhatsApp Cloud API / IA',
                'slug' => 'ai-chatbot-whatsapp',
                'description' => 'Bot conversacional conectado a base de conocimiento de la empresa para atención de consultas, toma de pedidos y alertas operativas.',
                'hours_dev' => 8.00,
                'hours_integration' => 14.00,
                'hours_testing_qa' => 16.00,
                'cost_setup_infra' => 60.00,
                'cost_monthly_infra' => 45.00,
                'is_preset_mining' => false,
                'is_preset_environment' => false,
                'is_preset_commerce' => false,
                'is_preset_industry' => false,
                'is_preset_services' => false,
                'is_recommended' => false,
            ],
            [
                'category' => 'IA & Automatizaciones',
                'name' => 'Notificaciones Automáticas Multicanal (Email / Push / SMS)',
                'slug' => 'notifications-multi-channel',
                'description' => 'Motor de envío de notificaciones transaccionales y recordatorios automáticos por Email (Mailgun/SES) y Web Push.',
                'hours_dev' => 4.00,
                'hours_integration' => 6.00,
                'hours_testing_qa' => 8.00,
                'cost_setup_infra' => 15.00,
                'cost_monthly_infra' => 20.00,
                'is_preset_mining' => true,
                'is_preset_environment' => true,
                'is_preset_commerce' => true,
                'is_preset_industry' => true,
                'is_preset_services' => true,
                'is_recommended' => true,
            ],

            // ==================== BUSINESS INTELLIGENCE & REPORTES ====================
            [
                'category' => 'Reportes & BI',
                'name' => 'Dashboard Ejecutivo de Métricas y KPIs en Tiempo Real',
                'slug' => 'executive-dashboard-kpis',
                'description' => 'Gráficos interactivos con Chart.js / ApexCharts, filtros por período y exportación instantánea a Excel y PDF.',
                'hours_dev' => 6.00,
                'hours_integration' => 8.00,
                'hours_testing_qa' => 10.00,
                'cost_setup_infra' => 0.00,
                'cost_monthly_infra' => 15.00,
                'is_preset_mining' => true,
                'is_preset_environment' => true,
                'is_preset_commerce' => true,
                'is_preset_industry' => true,
                'is_preset_services' => true,
                'is_recommended' => true,
            ],

            // ==================== INFRAESTRUCTURA & DEVOPS ====================
            [
                'category' => 'Infraestructura & DevOps',
                'name' => 'Despliegue Cloud Alta Disponibilidad + SSL + Backups Diarios',
                'slug' => 'cloud-infra-ssl-backups',
                'description' => 'Configuración de servidor optimizado con Docker, certificado SSL gratuito renovable, cortafuegos y copia de seguridad en S3.',
                'hours_dev' => 4.00,
                'hours_integration' => 8.00,
                'hours_testing_qa' => 10.00,
                'cost_setup_infra' => 75.00,
                'cost_monthly_infra' => 40.00,
                'is_preset_mining' => true,
                'is_preset_environment' => true,
                'is_preset_commerce' => true,
                'is_preset_industry' => true,
                'is_preset_services' => true,
                'is_recommended' => true,
            ],
        ];

        $feasibilityMap = [
            // ZONA AMARILLA
            'payment-gateway-integration' => [
                'status' => 'amarillo',
                'condition' => 'Requiere cuenta bancaria o de Mercado Pago / Stripe validada y con credenciales de producción provistas por el cliente.',
            ],
            'afip-invoicing-integration' => [
                'status' => 'amarillo',
                'condition' => 'El cliente debe proveer CUIT, clave fiscal y delegar certificados fiscales (CSR/alias fiscal en AFIP) a tiempo.',
            ],
            'production-orders-traceability' => [
                'status' => 'amarillo',
                'condition' => 'Exige mapeo previo de los estados de fabricación y flujos operativos de planta antes de iniciar el desarrollo.',
            ],
            'service-contracts-recurring-billing' => [
                'status' => 'amarillo',
                'condition' => 'Exige definición clara de días de corte, políticas de recargo por mora y ciclos de facturación acordados.',
            ],
            'appointment-booking-calendar' => [
                'status' => 'amarillo',
                'condition' => 'Solo turnos en plataforma interna con exportación de archivos .ics; no incluye sincronización bidireccional compleja con APIs de calendarios externos.',
            ],

            // ZONA ROJA
            'iot-sensors-mining' => [
                'status' => 'rojo',
                'script' => 'Nosotros implementamos el sistema de gestión operativa (CMMS y Calidad). Los operarios registran paradas y métricas desde tablets en planta en 5 segundos. No realizamos cableado ni conexiones eléctricas a PLC para no alterar las garantías de sus maquinarias.',
            ],
            'gis-geofencing-mining' => [
                'status' => 'rojo',
                'script' => 'El cálculo cartográfico satelital en tiempo real presenta desvíos por cobertura GPS de faena y costos elevados por peticiones de APIs. Proveemos geolocalización por puntos de control fijos y registro de coordenadas al inicio/fin de turnos.',
            ],
            'offline-sync-mobile' => [
                'status' => 'rojo',
                'script' => 'Nuestra plataforma está optimizada para cargar de forma ultra liviana con conexión móvil 3G/4G. Para zonas sin señal, implementamos un esquema ágil donde el técnico completa la planilla base y la sube en un clic al retornar al campamento o zona Wi-Fi, asegurando que ningún dato se sobreescriba ni se pierda.',
            ],
            'logistics-shipping-api' => [
                'status' => 'rojo',
                'script' => 'Para evitar que una caída del servidor del correo te deje sin ventas en el checkout, configuramos un cotizador por zonas y código postal con tarifas preestablecidas o retiro en sucursal. Es mucho más rápido y no frustra al comprador.',
            ],
            'ai-chatbot-whatsapp' => [
                'status' => 'rojo',
                'script' => 'Para proteger tu línea comercial contra bloqueos de Meta y evitar costos sorpresa por mensaje, integramos un botón directo a WhatsApp con mensaje predeterminado y un motor de notificaciones automáticas por Email y Web Push para que no pierdas ninguna consulta.',
            ],
            'iot-oee-factory-sensors' => [
                'status' => 'rojo',
                'script' => 'Nosotros implementamos el sistema de gestión operativa (CMMS y Calidad). Los operarios registran paradas y métricas desde tablets en planta en 5 segundos. No realizamos cableado ni conexiones eléctricas a PLC para no alterar las garantías de sus maquinarias.',
            ],
        ];

        foreach ($features as $featureData) {
            $slug = $featureData['slug'];
            $featureData['feasibility_status'] = $feasibilityMap[$slug]['status'] ?? 'verde';
            $featureData['feasibility_condition'] = $feasibilityMap[$slug]['condition'] ?? null;
            $featureData['contingency_script'] = $feasibilityMap[$slug]['script'] ?? null;

            Feature::updateOrCreate(['slug' => $slug], $featureData);
        }
    }
}
