<?php

namespace Database\Seeders;

use App\Models\Feature;
use App\Models\SoftwareType;
use Illuminate\Database\Seeder;

class FeatureSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $features = [
            // ==================== SEGURIDAD, ACCESO & ROLES ====================
            [
                'category' => 'Seguridad & Acceso',
                'name' => 'Autenticación Avanzada Multi-Rol y 2FA',
                'slug' => 'auth-multi-role-2fa',
                'description' => 'Control de acceso granular por permisos (Spatie/Policies), autenticación en 2 pasos (OTP/Authenticator) y registro de sesiones activas.',
                'hours_dev' => 6.00,
                'hours_integration' => 6.00,
                'hours_testing_qa' => 8.00,
                'cost_setup_infra' => 0.00,
                'cost_monthly_infra' => 15.00,
                'is_preset_mining' => true,
                'is_preset_environment' => true,
                'is_preset_commerce' => true,
                'is_recommended' => true,
            ],
            [
                'category' => 'Seguridad & Acceso',
                'name' => 'Auditoría de Acciones y Trazabilidad Forense',
                'slug' => 'audit-logs-compliance',
                'description' => 'Log inmutable de cambios (quién, qué, cuándo y desde qué IP) para cumplimiento de normas ISO 45001 / ISO 14001 y auditorías externas.',
                'hours_dev' => 5.00,
                'hours_integration' => 7.00,
                'hours_testing_qa' => 8.00,
                'cost_setup_infra' => 20.00,
                'cost_monthly_infra' => 25.00,
                'is_preset_mining' => true,
                'is_preset_environment' => true,
                'is_preset_commerce' => false,
                'is_recommended' => true,
            ],

            // ==================== MINERÍA, HSE & OPERACIONES EN FAENA ====================
            [
                'category' => 'Minería & HSE',
                'name' => 'Telemetría y Monitoreo de Sensores en Tiempo Real',
                'slug' => 'iot-sensors-mining',
                'description' => 'Recepción y procesamiento de datos de telemetría de maquinaria y sensores de gases/vibración vía WebSockets / MQTT.',
                'hours_dev' => 10.00,
                'hours_integration' => 14.00,
                'hours_testing_qa' => 16.00,
                'cost_setup_infra' => 80.00,
                'cost_monthly_infra' => 60.00,
                'is_preset_mining' => true,
                'is_preset_environment' => false,
                'is_preset_commerce' => false,
                'is_recommended' => true,
            ],
            [
                'category' => 'Minería & HSE',
                'name' => 'Mapeo GIS Satelital y Geofencing de Faena',
                'slug' => 'gis-geofencing-mining',
                'description' => 'Visualización de vehículos y cuadrillas en mapa interactivo con delimitación de zonas seguras y alertas de desvío.',
                'hours_dev' => 8.00,
                'hours_integration' => 12.00,
                'hours_testing_qa' => 12.00,
                'cost_setup_infra' => 50.00,
                'cost_monthly_infra' => 45.00,
                'is_preset_mining' => true,
                'is_preset_environment' => false,
                'is_preset_commerce' => false,
                'is_recommended' => false,
            ],
            [
                'category' => 'Minería & HSE',
                'name' => 'Sincronización Offline-First para Terreno',
                'slug' => 'offline-sync-mobile',
                'description' => 'Almacenamiento local en dispositivo móvil (IndexedDB / SQLite local) con sincronización bidireccional automática al recuperar conectividad.',
                'hours_dev' => 12.00,
                'hours_integration' => 16.00,
                'hours_testing_qa' => 20.00,
                'cost_setup_infra' => 30.00,
                'cost_monthly_infra' => 20.00,
                'is_preset_mining' => true,
                'is_preset_environment' => true,
                'is_preset_commerce' => false,
                'is_recommended' => true,
            ],
            [
                'category' => 'Minería & HSE',
                'name' => 'Gestión de Contratistas y Control de EPP',
                'slug' => 'contractors-epp-management',
                'description' => 'Validación de aptitud médica, ART, inducciones de seguridad y entrega de elementos de protección personal con firma digital.',
                'hours_dev' => 8.00,
                'hours_integration' => 8.00,
                'hours_testing_qa' => 10.00,
                'cost_setup_infra' => 0.00,
                'cost_monthly_infra' => 15.00,
                'is_preset_mining' => true,
                'is_preset_environment' => false,
                'is_preset_commerce' => false,
                'is_recommended' => false,
            ],

            // ==================== MEDIO AMBIENTE & SUSTENTABILIDAD ====================
            [
                'category' => 'Medio Ambiente',
                'name' => 'Módulo de Mediciones Ambientales (Agua, Aire, Suelo)',
                'slug' => 'environmental-measurements',
                'description' => 'Carga y validación de ensayos de laboratorio, comparación automática contra límites legales y alertas tempranas de excedencia.',
                'hours_dev' => 8.00,
                'hours_integration' => 10.00,
                'hours_testing_qa' => 12.00,
                'cost_setup_infra' => 0.00,
                'cost_monthly_infra' => 20.00,
                'is_preset_mining' => false,
                'is_preset_environment' => true,
                'is_preset_commerce' => false,
                'is_recommended' => true,
            ],
            [
                'category' => 'Medio Ambiente',
                'name' => 'Matriz de Cumplimiento Legal y Licencias Ambientales',
                'slug' => 'environmental-legal-matrix',
                'description' => 'Gestor de requisitos legales vigentes por provincia/nación, alertas de vencimiento de permisos y asignación de responsables.',
                'hours_dev' => 6.00,
                'hours_integration' => 8.00,
                'hours_testing_qa' => 10.00,
                'cost_setup_infra' => 0.00,
                'cost_monthly_infra' => 15.00,
                'is_preset_mining' => false,
                'is_preset_environment' => true,
                'is_preset_commerce' => false,
                'is_recommended' => true,
            ],
            [
                'category' => 'Medio Ambiente',
                'name' => 'Generador de Informes Técnicos y Balances de Carbono',
                'slug' => 'environmental-reports-carbon',
                'description' => 'Cálculo de huella de carbono, generación de reportes en PDF formal listos para presentación ante entes reguladores y autoridades mineras.',
                'hours_dev' => 7.00,
                'hours_integration' => 9.00,
                'hours_testing_qa' => 12.00,
                'cost_setup_infra' => 25.00,
                'cost_monthly_infra' => 20.00,
                'is_preset_mining' => true,
                'is_preset_environment' => true,
                'is_preset_commerce' => false,
                'is_recommended' => false,
            ],

            // ==================== E-COMMERCE & COMERCIO ====================
            [
                'category' => 'Comercio & Pagos',
                'name' => 'Catálogo Inteligente, Filtros y Carrito de Compras',
                'slug' => 'catalog-cart-commerce',
                'description' => 'Gestión de productos con variantes (talle, color, especificaciones), buscador predictivo, listas de precios mayoristas y carrito persistente.',
                'hours_dev' => 8.00,
                'hours_integration' => 8.00,
                'hours_testing_qa' => 10.00,
                'cost_setup_infra' => 0.00,
                'cost_monthly_infra' => 15.00,
                'is_preset_mining' => false,
                'is_preset_environment' => false,
                'is_preset_commerce' => true,
                'is_recommended' => true,
            ],
            [
                'category' => 'Comercio & Pagos',
                'name' => 'Pasarela de Pagos (Mercado Pago / Stripe / Transferencia)',
                'slug' => 'payment-gateway-integration',
                'description' => 'Checkout transparente, webhooks de confirmación automática de pagos, suscripciones recurrentes y soporte multi-moneda.',
                'hours_dev' => 6.00,
                'hours_integration' => 10.00,
                'hours_testing_qa' => 14.00,
                'cost_setup_infra' => 40.00,
                'cost_monthly_infra' => 20.00,
                'is_preset_mining' => false,
                'is_preset_environment' => false,
                'is_preset_commerce' => true,
                'is_recommended' => true,
            ],
            [
                'category' => 'Comercio & Pagos',
                'name' => 'Facturación Electrónica AFIP / Facturación Automática',
                'slug' => 'afip-invoicing-integration',
                'description' => 'Integración directa con Web Services de AFIP (WSFE) para emisión instantánea de Facturas A, B, C y Notas de Crédito con CAE.',
                'hours_dev' => 6.00,
                'hours_integration' => 12.00,
                'hours_testing_qa' => 16.00,
                'cost_setup_infra' => 50.00,
                'cost_monthly_infra' => 30.00,
                'is_preset_mining' => false,
                'is_preset_environment' => false,
                'is_preset_commerce' => true,
                'is_recommended' => true,
            ],
            [
                'category' => 'Comercio & Pagos',
                'name' => 'Integración Logística y Envíos (Andreani, Correo, OCA)',
                'slug' => 'logistics-shipping-api',
                'description' => 'Cotizador de envíos en tiempo real en checkout, generación de etiquetas de despacho con código de barras y tracking para el comprador.',
                'hours_dev' => 5.00,
                'hours_integration' => 9.00,
                'hours_testing_qa' => 12.00,
                'cost_setup_infra' => 30.00,
                'cost_monthly_infra' => 20.00,
                'is_preset_mining' => false,
                'is_preset_environment' => false,
                'is_preset_commerce' => true,
                'is_recommended' => false,
            ],

            // ==================== AUTOMATIZACIÓN, IA & CHATBOTS ====================
            [
                'category' => 'IA & Automatizaciones',
                'name' => 'Chatbot Inteligente con WhatsApp Cloud API / IA',
                'slug' => 'ai-chatbot-whatsapp',
                'description' => 'Bot conversacional conectado a base de conocimiento de la empresa para atención de consultas, toma de pedidos y alertas operativas.',
                'hours_dev' => 8.00,
                'hours_integration' => 14.00,
                'hours_testing_qa' => 16.00,
                'cost_setup_infra' => 60.00,
                'cost_monthly_infra' => 45.00,
                'is_preset_mining' => false,
                'is_preset_environment' => false,
                'is_preset_commerce' => true,
                'is_recommended' => false,
            ],
            [
                'category' => 'IA & Automatizaciones',
                'name' => 'Notificaciones Automáticas Multicanal (Email / Push / SMS)',
                'slug' => 'notifications-multi-channel',
                'description' => 'Motor de envío de notificaciones transaccionales y recordatorios automáticos por Email (Mailgun/SES) y Web Push.',
                'hours_dev' => 4.00,
                'hours_integration' => 6.00,
                'hours_testing_qa' => 8.00,
                'cost_setup_infra' => 15.00,
                'cost_monthly_infra' => 20.00,
                'is_preset_mining' => true,
                'is_preset_environment' => true,
                'is_preset_commerce' => true,
                'is_recommended' => true,
            ],

            // ==================== BUSINESS INTELLIGENCE & REPORTES ====================
            [
                'category' => 'Reportes & BI',
                'name' => 'Dashboard Ejecutivo de Métricas y KPIs en Tiempo Real',
                'slug' => 'executive-dashboard-kpis',
                'description' => 'Gráficos interactivos con Chart.js / ApexCharts, filtros por período y exportación instantánea a Excel y PDF.',
                'hours_dev' => 6.00,
                'hours_integration' => 8.00,
                'hours_testing_qa' => 10.00,
                'cost_setup_infra' => 0.00,
                'cost_monthly_infra' => 15.00,
                'is_preset_mining' => true,
                'is_preset_environment' => true,
                'is_preset_commerce' => true,
                'is_recommended' => true,
            ],

            // ==================== INFRAESTRUCTURA & DEVOPS ====================
            [
                'category' => 'Infraestructura & DevOps',
                'name' => 'Despliegue Cloud Alta Disponibilidad + SSL + Backups Diarios',
                'slug' => 'cloud-infra-ssl-backups',
                'description' => 'Configuración de servidor optimizado con Docker, certificado SSL gratuito renovable, cortafuegos y copia de seguridad en S3.',
                'hours_dev' => 4.00,
                'hours_integration' => 8.00,
                'hours_testing_qa' => 10.00,
                'cost_setup_infra' => 75.00,
                'cost_monthly_infra' => 40.00,
                'is_preset_mining' => true,
                'is_preset_environment' => true,
                'is_preset_commerce' => true,
                'is_recommended' => true,
            ],
        ];

        foreach ($features as $featureData) {
            Feature::firstOrCreate(['slug' => $featureData['slug']], $featureData);
        }
    }
}
